import type { Company, Rider, Order } from "./types";

export const COMPANIES: Company[] = [
  { name:"Lagos Express Co.", ini:"LE", clr:"bg-blue-100 text-blue-700", type:"Local", city:"Lagos", riders:45, orders:312, status:"active", applied:"3 months ago", fleet:"45 motorcycles", plan:"Pro", desc:"Premium last-mile delivery across Lagos metropolis.", contact:{name:"Ade Balogun",email:"ade@lagosexpress.ng",phone:"+234 801 234 5678"}, legal:{reg:"Lagos Express Couriers Ltd.",cac:"RC-1234567",addr:"14 Allen Avenue, Ikeja, Lagos"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"SwiftMove Nigeria", ini:"SM", clr:"bg-green-100 text-green-700", type:"Local", city:"Abuja", riders:28, orders:186, status:"active", applied:"2 months ago", fleet:"28 motorcycles", plan:"Pro", desc:"Same-day delivery specialists in Abuja and satellite towns.", contact:{name:"Musa Aliyu",email:"musa@swiftmove.ng",phone:"+234 802 345 6789"}, legal:{reg:"SwiftMove Nigeria Ltd.",cac:"RC-2345678",addr:"Plot 4 Wuse Zone 6, Abuja"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"NationLink Interstate", ini:"NI", clr:"bg-purple-100 text-purple-700", type:"Interstate", city:"Lagos", riders:0, orders:94, status:"active", applied:"4 months ago", fleet:"8 trucks, 3 vans", plan:"Enterprise", desc:"Cross-state freight and parcel delivery across Nigeria.", contact:{name:"Chidi Okonkwo",email:"chidi@nationlink.ng",phone:"+234 803 456 7890"}, legal:{reg:"NationLink Logistics Services Ltd.",cac:"RC-3456789",addr:"22 Apapa Road, Lagos Island"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"QuickDash PH", ini:"QD", clr:"bg-orange-100 text-orange-700", type:"Local", city:"Port Harcourt", riders:19, orders:127, status:"active", applied:"2 months ago", fleet:"19 motorcycles", plan:"Pro", desc:"Fastest local deliveries in Port Harcourt and environs.", contact:{name:"Emeka Nwosu",email:"emeka@quickdash.ng",phone:"+234 804 567 8901"}, legal:{reg:"QuickDash Couriers Ltd.",cac:"RC-4567890",addr:"7 Aba Road, Port Harcourt"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"CrossState Ltd.", ini:"CS", clr:"bg-indigo-100 text-indigo-700", type:"Interstate", city:"Ibadan", riders:0, orders:61, status:"active", applied:"5 months ago", fleet:"5 trucks", plan:"Pro", desc:"Ibadan-based interstate logistics connecting South-West Nigeria.", contact:{name:"Biodun Afolabi",email:"biodun@crossstate.ng",phone:"+234 805 678 9012"}, legal:{reg:"CrossState Logistics Ltd.",cac:"RC-5678901",addr:"Ring Road, Ibadan"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"RapidRun Kano", ini:"RK", clr:"bg-yellow-100 text-yellow-700", type:"Local", city:"Kano", riders:11, orders:78, status:"active", applied:"3 months ago", fleet:"11 motorcycles", plan:"Starter", desc:"Local courier services across Kano city.", contact:{name:"Yakubu Musa",email:"yakubu@rapidrun.ng",phone:"+234 806 789 0123"}, legal:{reg:"RapidRun Couriers",cac:"RC-6789012",addr:"Sabon Gari, Kano"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"SpeedyLink Enugu", ini:"SE", clr:"bg-teal-100 text-teal-700", type:"Local", city:"Enugu", riders:8, orders:45, status:"active", applied:"1 month ago", fleet:"8 motorcycles", plan:"Starter", desc:"Local delivery in Enugu and Coal City environs.", contact:{name:"Ngozi Eze",email:"ngozi@speedylink.ng",phone:"+234 807 890 1234"}, legal:{reg:"SpeedyLink Courier Services",cac:"RC-7890123",addr:"Independence Layout, Enugu"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"PanAfrica Logistics", ini:"PA", clr:"bg-red-100 text-red-700", type:"Interstate", city:"Lagos", riders:0, orders:38, status:"suspended", applied:"6 months ago", fleet:"4 trucks", plan:"Pro", desc:"Pan-African freight forwarding and interstate delivery.", contact:{name:"Tunde Adeyemi",email:"tunde@panafrica.ng",phone:"+234 808 901 2345"}, legal:{reg:"PanAfrica Logistics Ltd.",cac:"RC-8901234",addr:"Tin Can Island, Apapa, Lagos"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"City Couriers Ibadan", ini:"CC", clr:"bg-pink-100 text-pink-700", type:"Local", city:"Ibadan", riders:14, orders:89, status:"active", applied:"2 months ago", fleet:"14 motorcycles", plan:"Pro", desc:"Reliable same-day delivery across Ibadan.", contact:{name:"Ola Akintunde",email:"ola@citycouriers.ng",phone:"+234 809 012 3456"}, legal:{reg:"City Couriers Ibadan Ltd.",cac:"RC-9012345",addr:"New Bodija, Ibadan"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"MetroDash Benin", ini:"MB", clr:"bg-cyan-100 text-cyan-700", type:"Local", city:"Benin City", riders:9, orders:52, status:"active", applied:"1 month ago", fleet:"9 motorcycles", plan:"Starter", desc:"Benin City local delivery network.", contact:{name:"Osaro Iyamu",email:"osaro@metrodash.ng",phone:"+234 810 123 4567"}, legal:{reg:"MetroDash Courier Ltd.",cac:"RC-0123456",addr:"Sapele Road, Benin City"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"verified"},{label:"Proof of Address",icon:"map-pin",st:"verified"}]},
  { name:"ZippyRide Abuja", ini:"ZR", clr:"bg-neutral-100 text-neutral-700", type:"Local", city:"Abuja", riders:0, orders:0, status:"pending", applied:"2 days ago", fleet:"12 motorcycles", plan:"Pro", desc:"Fast same-day delivery across Abuja and its suburbs. Specialising in e-commerce last-mile and food delivery.", contact:{name:"Bello Ibrahim",email:"bello@zippyride.ng",phone:"+234 811 234 5678"}, legal:{reg:"ZippyRide Couriers Ltd.",cac:"RC-1122334",addr:"Gwarinpa Estate, Abuja"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"pending"},{label:"Vehicle Insurance",icon:"shield-check",st:"pending"},{label:"Proof of Address",icon:"map-pin",st:"pending"}]},
  { name:"NordLine Logistics", ini:"NL", clr:"bg-purple-100 text-purple-700", type:"Interstate", city:"Lagos", riders:0, orders:0, status:"pending", applied:"1 day ago", fleet:"6 trucks, 2 vans", plan:"Enterprise", desc:"Pan-Nigerian interstate logistics focusing on fragile and high-value cargo. Lagos, Abuja, PH and Kano corridors.", contact:{name:"Femi Olanrewaju",email:"femi@nordline.ng",phone:"+234 812 345 6789"}, legal:{reg:"NordLine Freight Services Ltd.",cac:"RC-2233445",addr:"Ajao Estate, Lagos"}, docs:[{label:"CAC Certificate",icon:"file-text",st:"verified"},{label:"Director ID (NIN)",icon:"user-check",st:"verified"},{label:"Tax Clearance Certificate",icon:"receipt",st:"verified"},{label:"Vehicle Insurance",icon:"shield-check",st:"flagged"},{label:"Proof of Address",icon:"map-pin",st:"pending"}]},
];

export const COMPANY_RIDERS: Rider[] = [
  { id:1, name:"Emeka Okafor",   vehicle:"Motorcycle", zone:"Ikeja",    orders:24, rating:4.9, status:"online",  busy:true  },
  { id:2, name:"Aisha Ibrahim",  vehicle:"Bicycle",    zone:"Lekki",    orders:18, rating:4.7, status:"online",  busy:true  },
  { id:3, name:"Chidi Obiora",   vehicle:"Motorcycle", zone:"VI",       orders:31, rating:4.8, status:"online",  busy:false },
  { id:4, name:"Bola Oluwaseun", vehicle:"Motorcycle", zone:"Surulere", orders:12, rating:4.6, status:"offline", busy:false },
  { id:5, name:"Funmi Adeyemi",  vehicle:"Bicycle",    zone:"Yaba",     orders:20, rating:4.5, status:"online",  busy:true  },
  { id:6, name:"Kola Badmus",    vehicle:"Car/Van",    zone:"Mainland", orders:8,  rating:4.7, status:"offline", busy:false },
  { id:7, name:"Ngozi Eze",      vehicle:"Motorcycle", zone:"Ajah",     orders:16, rating:4.9, status:"online",  busy:false },
  { id:8, name:"Tunde Sanni",    vehicle:"Motorcycle", zone:"Ikotun",   orders:22, rating:4.6, status:"online",  busy:true  },
  { id:9, name:"Yemi Obi",       vehicle:"Bicycle",    zone:"Gbagada",  orders:14, rating:4.4, status:"online",  busy:false },
];

export const COMPANY_ORDERS: Order[] = [
  { id:"ORD-00481", customer:"Tunde Adeyemi",  route:"Ikeja → Lekki",        type:"Local",       status:"transit",    rider:"Emeka O."   },
  { id:"ORD-00480", customer:"Amaka Obi",       route:"Surulere → VI",         type:"Local",       status:"assigned",   rider:"Chidi O."   },
  { id:"ORD-00479", customer:"Femi Balogun",    route:"Yaba → Gbagada",        type:"Local",       status:"processing", rider:null         },
  { id:"ORD-00478", customer:"Chioma Nwosu",    route:"Maryland → Festac",     type:"Local",       status:"delivered",  rider:"Funmi A."   },
  { id:"ORD-00477", customer:"Biodun Aina",     route:"Ikeja → Ikorodu",       type:"Local",       status:"processing", rider:null         },
  { id:"ORD-00476", customer:"Shade Akande",    route:"Lagos → Benin City",    type:"Interstate",  status:"processing", rider:null         },
];

export const RIDER_ORDERS: Order[] = [
  { id:"ORD-00481", customer:"Tunde Adeyemi",  phone:"+234 812 345 6789", pickup:"Ikeja Bus Stop",   dropoff:"Lekki Phase 1",  distance:"18 km", time:"25 min", earn:"₦650",  status:"transit"   },
  { id:"ORD-00480", customer:"Amaka Obi",       phone:"+234 803 456 7890", pickup:"Surulere Market", dropoff:"Victoria Island", distance:"12 km", time:"18 min", earn:"₦500",  status:"assigned"  },
  { id:"ORD-00479", customer:"Femi Balogun",    phone:"+234 701 234 5678", pickup:"Yaba Tech",       dropoff:"Gbagada",        distance:"8 km",  time:"12 min", earn:"₦400",  status:"pending"   },
  { id:"ORD-00478", customer:"Chioma Nwosu",    phone:"+234 906 789 0123", pickup:"Maryland Mall",   dropoff:"Festac Town",    distance:"15 km", time:"22 min", earn:"₦580",  status:"delivered" },
  { id:"ORD-00477", customer:"Biodun Aina",     phone:"+234 814 567 8901", pickup:"Ojota Park",      dropoff:"Ikorodu",        distance:"22 km", time:"35 min", earn:"₦750",  status:"delivered" },
  { id:"ORD-00476", customer:"Shade Akande",    phone:"+234 802 345 6789", pickup:"Ikeja GRA",       dropoff:"Lekki",          distance:"20 km", time:"28 min", earn:"₦680",  status:"rejected"  },
];

export const ADMIN_DELIVERIES = [
  { id:"ORD-00481", company:"Lagos Express",  customer:"Tunde Adeyemi",  route:"Ikeja → Lekki",           type:"Local",      rider:"Emeka R.",  status:"transit",    time:"2m ago"  },
  { id:"ORD-00480", company:"SwiftMove",      customer:"Amaka Obi",       route:"Abuja → Gwagwalada",      type:"Local",      rider:"Aisha R.",  status:"delivered",  time:"18m ago" },
  { id:"ORD-00479", company:"NationLink",     customer:"Chinyere Eze",    route:"Lagos → Enugu",           type:"Interstate", rider:"N/A",       status:"processing", time:"35m ago" },
  { id:"ORD-00478", company:"Lagos Express",  customer:"Biodun Aina",     route:"Surulere → VI",           type:"Local",      rider:"Chidi R.",  status:"transit",    time:"42m ago" },
  { id:"ORD-00477", company:"QuickDash PH",   customer:"Blessing Moses",  route:"GRA → Old GRA",           type:"Local",      rider:"Bola R.",   status:"delivered",  time:"1hr ago" },
];

export const ALL_RIDERS = [
  { name:"Emeka Okafor",   company:"Lagos Express", vehicle:"Motorcycle", city:"Lagos",        orders:24, rating:4.9, status:"online"  },
  { name:"Aisha Ibrahim",  company:"SwiftMove",     vehicle:"Bicycle",    city:"Abuja",        orders:18, rating:4.7, status:"online"  },
  { name:"Chidi Obiora",   company:"Lagos Express", vehicle:"Motorcycle", city:"Lagos",        orders:31, rating:4.8, status:"online"  },
  { name:"Bola Oluwaseun", company:"QuickDash PH",  vehicle:"Motorcycle", city:"Port Harcourt",orders:12, rating:4.6, status:"offline" },
];
